name: Bump dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 1 * *'  # At 08:00 on day-of-month 1

jobs:
  bump-dependencies:
    if: ${{ github.event_name != 'schedule' || github.repository == 'saleor/saleor' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v6.0.0
        with:
          enable-cache: false

      - run: python -m pip install pre-commit
      - run: uv lock --upgrade
      - run: pre-commit autoupdate
      - run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412  # v7.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump-dependencies
          delete-branch: true
          commit-message: Bump dependencies
          title: 'Bump dependencies'
          body: |
            Monthly update of backend dependencies.
          labels: |
            :robot: bot
            test deployment
